### ISSUE TITLE
Please update Catch2

### ISSUE THREAD

**Issue by hmenke** [krivenko/libcommute#2]
I'm currently being bitten by this bug https://github.com/catchorg/Catch2/issues/2178 which has been fixed in [v2.13.5](https://github.com/catchorg/Catch2/releases/tag/v2.13.5) and later. libcommute currently uses [v2.7.2](https://github.com/krivenko/libcommute/blob/863b67380742b4431b9170fbcdf51ff81172db0e/test/catch2/catch.hpp#L2).

Please also consider making use of Catch2's CMake integration: https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md

**Comment by krivenko** [comment]
Dear @hmenke,

Thank you for pointing this out. I have upgraded the bundled Catch2 to the most recent release (v2.13.9).

Speaking of the CMake integration, I would rather wait until Catch2 v3.0.0 is released. They are going to move to a different distribution model (a statically compiled library and multiple headers), which will also affect the CMake code.
